import fs from 'node:fs';
import path from 'node:path';
import { spawn } from 'node:child_process';

export const DSPY_CAPABILITY='reasoning.dspy@1.0.0' as const;
export const DSPY_REVISION='ba3f9198efe5d125c7c1a2b40b1f1e6166209bd2' as const;
export type DSPyState='PASS'|'FAIL'|'DEGRADED';
export interface DSPyRequest{signature?:string;inputs:Record<string,unknown>;model?:string;temperature?:number;}
export interface DSPyEvidence{state:DSPyState;code?:string;provider:'stanfordnlp/dspy';revision:typeof DSPY_REVISION;root:string;python:string;enabled:boolean;sourcePresent:boolean;model:string;credentialsPresent:boolean;}
const env=(name:string,fallback='')=>(process.env[name]??fallback).trim();
const enabled=()=>/^(1|true|yes)$/i.test(env('SOUL_N06_DSPY_ENABLED'));
function config(){return {python:env('SOUL_N06_DSPY_PYTHON','python3'),root:path.resolve(env('SOUL_N06_DSPY_ROOT','integrations/soul-upstream/dspy')),model:env('SOUL_N06_DSPY_MODEL','openai/gpt-5-mini'),credentialsPresent:Boolean(env('OPENAI_API_KEY')),timeoutMs:Math.max(10000,Number.parseInt(env('SOUL_N06_DSPY_TIMEOUT_MS','120000'),10)||120000)}}
export function describeDSPyAdapter():DSPyEvidence{const c=config();const sourcePresent=fs.existsSync(c.root)&&fs.statSync(c.root).isDirectory();if(!enabled())return {state:'DEGRADED',code:'DSPY_ADAPTER_DISABLED',provider:'stanfordnlp/dspy',revision:DSPY_REVISION,root:c.root,python:c.python,enabled:false,sourcePresent,model:c.model,credentialsPresent:c.credentialsPresent};if(!sourcePresent)return {state:'DEGRADED',code:'DSPY_SOURCE_NOT_AVAILABLE',provider:'stanfordnlp/dspy',revision:DSPY_REVISION,root:c.root,python:c.python,enabled:true,sourcePresent:false,model:c.model,credentialsPresent:c.credentialsPresent};if(!c.credentialsPresent)return {state:'DEGRADED',code:'DSPY_OPENAI_CREDENTIALS_NOT_AVAILABLE',provider:'stanfordnlp/dspy',revision:DSPY_REVISION,root:c.root,python:c.python,enabled:true,sourcePresent:true,model:c.model,credentialsPresent:false};return {state:'DEGRADED',code:'DSPY_EXECUTION_NOT_YET_PROVEN',provider:'stanfordnlp/dspy',revision:DSPY_REVISION,root:c.root,python:c.python,enabled:true,sourcePresent:true,model:c.model,credentialsPresent:true};}
export async function runDSPy(request:DSPyRequest):Promise<Record<string,unknown>>{const evidence=describeDSPyAdapter();if(evidence.state!=='DEGRADED'||evidence.code!=='DSPY_EXECUTION_NOT_YET_PROVEN')return {...evidence,capability:DSPY_CAPABILITY};const c=config();const signature=(request.signature||'question -> answer').trim();if(!signature)return {state:'FAIL',code:'DSPY_SIGNATURE_REQUIRED',capability:DSPY_CAPABILITY,...evidence};if(!request.inputs||typeof request.inputs!=='object')return {state:'FAIL',code:'DSPY_INPUTS_REQUIRED',capability:DSPY_CAPABILITY,...evidence};const payload=JSON.stringify({root:c.root,model:request.model?.trim()||c.model,signature,inputs:request.inputs,temperature:typeof request.temperature==='number'?request.temperature:0.2});const child=spawn(c.python,[path.resolve('scripts/dspy_runner.py')],{cwd:process.cwd(),stdio:['pipe','pipe','pipe']});let stdout='',stderr='';child.stdout.setEncoding('utf8');child.stderr.setEncoding('utf8');child.stdout.on('data',x=>stdout+=x);child.stderr.on('data',x=>stderr+=x);const result=await new Promise<{code:number|null;signal:NodeJS.Signals|null}>((resolve,reject)=>{const timer=setTimeout(()=>{child.kill('SIGTERM');reject(new Error('DSPY_TIMEOUT'));},c.timeoutMs);child.once('error',e=>{clearTimeout(timer);reject(e)});child.once('exit',(code,signal)=>{clearTimeout(timer);resolve({code,signal})});child.stdin.end(payload)}).catch(error=>({code:null,signal:null,error}));if('error'in result&&result.error){const message=result.error instanceof Error?result.error.message:String(result.error);return {state:message==='DSPY_TIMEOUT'?'FAIL':'DEGRADED',code:message==='DSPY_TIMEOUT'?'DSPY_TIMEOUT':'DSPY_PROCESS_UNAVAILABLE',detail:message,stderr:stderr.slice(-4000),capability:DSPY_CAPABILITY,...evidence};}if(result.code!==0)return {state:'FAIL',code:'DSPY_PROCESS_FAILED',exitCode:result.code,signal:result.signal,stderr:stderr.slice(-4000),capability:DSPY_CAPABILITY,...evidence};try{return {...JSON.parse(stdout.trim()),capability:DSPY_CAPABILITY,providerRevision:DSPY_REVISION};}catch{return {state:'FAIL',code:'DSPY_INVALID_RUNNER_OUTPUT',stdout:stdout.slice(-4000),stderr:stderr.slice(-4000),capability:DSPY_CAPABILITY,...evidence};}}
