export const SOUL_MESH_PROTOCOL = 'soul-mesh/1' as const;
export const SOUL_NUCLEI = ['N01','N02','N03','N04','N05','N06'] as const;
export type SoulNucleus = typeof SOUL_NUCLEI[number];
export type SoulMeshKind = 'request' | 'response' | 'event' | 'error' | 'ack';
export type SoulMeshTransportKind = 'IN_PROCESS' | 'WEBVIEW_BRIDGE' | 'LOOPBACK_HTTP' | 'HTTP' | 'REALTIME';
export interface SoulMeshMessage<T = unknown> { protocol: typeof SOUL_MESH_PROTOCOL; id: string; correlationId: string; source: SoulNucleus; target: SoulNucleus; kind: SoulMeshKind; capability?: string; payload: T; timestamp: number; transport?: SoulMeshTransportKind; }
export interface SoulMeshTransport { send(message: SoulMeshMessage): Promise<void>; onMessage(handler: (message: SoulMeshMessage) => void | Promise<void>): () => void; }
export function createSoulMeshMessage<T>(input: Omit<SoulMeshMessage<T>, 'protocol' | 'id' | 'timestamp'>): SoulMeshMessage<T> { return { protocol: SOUL_MESH_PROTOCOL, id: crypto.randomUUID(), timestamp: Date.now(), ...input }; }
export function isSoulMeshMessage(value: unknown): value is SoulMeshMessage { if (!value || typeof value !== 'object') return false; const m = value as Record<string, unknown>; return m.protocol === SOUL_MESH_PROTOCOL && typeof m.id === 'string' && m.id.length > 0 && typeof m.correlationId === 'string' && m.correlationId.length > 0 && (SOUL_NUCLEI as readonly string[]).includes(m.source as string) && (SOUL_NUCLEI as readonly string[]).includes(m.target as string) && m.source !== m.target && typeof m.kind === 'string' && ['request','response','event','error','ack'].includes(m.kind) && (m.capability === undefined || (typeof m.capability === 'string' && m.capability.length > 0)) && typeof m.timestamp === 'number' && Number.isFinite(m.timestamp) && (m.transport === undefined || (['IN_PROCESS','WEBVIEW_BRIDGE','LOOPBACK_HTTP','HTTP','REALTIME'] as readonly string[]).includes(m.transport as string)); }
