export type Listener<T=unknown>=(data:T)=>void|Promise<void>;
class EventBus{private m=new Map<string,Set<Listener<unknown>>>();on<T>(e:string,l:Listener<T>){const s=this.m.get(e)||new Set();s.add(l as Listener<unknown>);this.m.set(e,s);return()=>this.off(e,l)}off<T>(e:string,l:Listener<T>){const s=this.m.get(e);if(!s)return;s.delete(l as Listener<unknown>);if(!s.size)this.m.delete(e)}emit<T>(e:string,d:T){for(const l of [...(this.m.get(e)||[])])void Promise.resolve(l(d))}getRegisteredEvents(){return [...this.m.keys()].sort()}};
class HortaCore{private d=new Map<string,unknown>();set<T>(k:string,v:T){this.d.set(k,v);return v}get<T>(k:string){return this.d.get(k) as T|undefined}has(k:string){return this.d.has(k)}snapshot(){return Object.fromEntries(this.d)}}
export interface NeuralModuleRegistration{id:string;type:"engine"|"ui";version:string;capabilities:readonly string[];dependencies:readonly string[]}
class Wormhole{private m=new Map<string,unknown>();private s=new Map<string,NeuralModuleRegistration>();register(id:string,c:unknown,r:Omit<NeuralModuleRegistration,"id">){if(this.m.has(id))throw new Error("AETERNUM_CONSCIOUSNESS_DUPLICATE_MODULE:"+id);this.m.set(id,c);this.s.set(id,{id,...r})}get<T>(id:string){return this.m.get(id) as T|undefined}list(){return [...this.s.values()].sort((a,b)=>a.id.localeCompare(b.id))}}
export const nervoVago=new EventBus();export const hortaCore=new HortaCore();export const wormhole=new Wormhole();
export interface MetaThought{input:string;output:string;metadata?:Record<string,unknown>;timestamp:number;latencyMs:number}
export type MetaThoughtExecutor=(query:string,context?:unknown)=>Promise<{output:string;metadata?:Record<string,unknown>}>;
export class MetaConsciousnessModule{readonly id="meta-consciousness";private active=false;private thoughts:MetaThought[]=[];
constructor(private readonly executor?:MetaThoughtExecutor){wormhole.register(this.id,this,{type:"engine",version:"1.0.0",capabilities:["meta-cognition","reasoning","reflection","abstraction"],dependencies:["aeternum.consciousness.eventBus","aeternum.consciousness.hortaCore"]});nervoVago.on("meta.activate",()=>this.activate());nervoVago.on("meta.deactivate",()=>this.deactivate());nervoVago.on<{query:string;context?:unknown}>("meta.think",d=>void this.think(d));nervoVago.on<{context?:unknown}>("meta.reflect",d=>void this.reflect(d));this.active=hortaCore.get<boolean>(this.id+".active")??false}
activate(){this.active=true;hortaCore.set(this.id+".active",true);hortaCore.set(this.id+".activatedAt",Date.now());nervoVago.emit("module.activated",{module:this.id})}
deactivate(){this.active=false;hortaCore.set(this.id+".active",false);nervoVago.emit("module.deactivated",{module:this.id})}
async think(d:{query:string;context?:unknown}){if(!this.active)return void nervoVago.emit("meta.error",{module:this.id,message:"Módulo inativo"});const q=d.query.trim();if(!q)return;if(!this.executor)return void nervoVago.emit("meta.unbound",{module:this.id,reason:"executor cognitivo não conectado"});const t=Date.now();try{const r=await this.executor(q,d.context);const thought={input:q,output:r.output,metadata:r.metadata,timestamp:Date.now(),latencyMs:Date.now()-t};this.thoughts=[...this.thoughts,thought].slice(-200);nervoVago.emit("meta.result",thought)}catch(e){nervoVago.emit("meta.error",{module:this.id,message:"Falha no executor cognitivo",error:e instanceof Error?e.message:String(e)})}}
async reflect(d:{context?:unknown}){if(!this.active)return;nervoVago.emit("meta.reflection",{module:this.id,thoughtCount:this.thoughts.length,activeMode:hortaCore.get("active.mode")??null,context:d.context,timestamp:Date.now()})}
getThoughtChain(){return [...this.thoughts]}}
export const metaConsciousnessModule=new MetaConsciousnessModule();
