import { NextResponse } from 'next/server';
import type { SoulMeshMessage } from '@/lib/soul-mesh/SoulMeshProtocol';
import { executeN06Capability, getN06Capabilities } from '@/lib/soul-mesh/N06CapabilityDispatcher';
import { N06AgentRegistry } from '@/lib/soul-mesh/N06AgentRegistry';
import { nucleus06Processor } from '@/lib/soul-core/N06Processor';
import { NUCLEUS_06_TOOL_IDS } from '@/lib/soul-core/Nucleus05ToolRegistry';
import { probeAllN06Peers } from '@/lib/soul-mesh/N06PeerAdapter';

const NUCLEUS_ID='N06' as const;
const NUCLEI=new Set(['N01','N02','N03','N04','N05','N06']);
const PEERS=['N01','N02','N03','N04','N05'] as const;
const MAX_PAYLOAD_BYTES=1024*1024;
const MAX_CLOCK_SKEW_MS=5*60*1000;
const MAX_ID_LENGTH=200;
const MAX_CAPABILITY_LENGTH=200;
function authorized(request:Request){const token=process.env.SOUL_MESH_TOKEN;return !token||request.headers.get('authorization')===`Bearer ${token}`;}
function result(message:SoulMeshMessage,kind:'response'|'error',payload:unknown,status=200){return NextResponse.json({protocol:'soul-mesh/1',id:crypto.randomUUID(),correlationId:message.correlationId,source:NUCLEUS_ID,target:message.source,kind,capability:message.capability,payload,timestamp:Date.now(),transport:'HTTP'} satisfies SoulMeshMessage,{status});}
function createN06Agents(){const registry=new N06AgentRegistry();const executable=nucleus06Processor.executableCapabilities();registry.register({id:'N06-cognitive-agent',name:'N06 Cognitive Agent',capabilities:executable,execute:m=>executeN06Capability(m.capability!,m.payload)});registry.register({id:'N06-tool-agent',name:'N06 Tool Agent',capabilities:NUCLEUS_06_TOOL_IDS.map(id=>`tool:${id}`),execute:m=>executeN06Capability(m.capability!,m.payload)});registry.register({id:'N06-mesh-agent',name:'N06 Mesh Agent',capabilities:['mesh.ping','mesh.describe','mesh.discovery'],execute:async m=>m.capability==='mesh.ping'?{ok:true,nucleus:NUCLEUS_ID,processedAt:Date.now()}:m.capability==='mesh.discovery'?{nucleus:NUCLEUS_ID,peers:await probeAllN06Peers()}: {nucleus:NUCLEUS_ID,peers:[...PEERS],declaredCapabilities:getN06Capabilities(),executableCapabilities:executable,agents:registry.describe(),inChannels:PEERS.map(peer=>`N06.IN.${peer}`),outChannels:PEERS.map(peer=>`N06.OUT.${peer}`)}});return registry;}
function validMessage(message:unknown):message is SoulMeshMessage{if(!message||typeof message!=='object')return false;const value=message as Record<string,unknown>;return value.protocol==='soul-mesh/1'&&typeof value.id==='string'&&value.id.length>0&&value.id.length<=MAX_ID_LENGTH&&typeof value.correlationId==='string'&&value.correlationId.length>0&&value.correlationId.length<=MAX_ID_LENGTH&&typeof value.source==='string'&&NUCLEI.has(value.source)&&value.target===NUCLEUS_ID&&value.source!==NUCLEUS_ID&&value.kind==='request'&&typeof value.capability==='string'&&value.capability.trim().length>0&&value.capability.length<=MAX_CAPABILITY_LENGTH&&Number.isFinite(value.timestamp)&&Math.abs(Date.now()-Number(value.timestamp))<=MAX_CLOCK_SKEW_MS;}
export async function GET(){return NextResponse.json({ok:true,nucleus:NUCLEUS_ID,protocol:'soul-mesh/1',peers:[...PEERS],capabilities:getN06Capabilities(),agents:createN06Agents().describe(),channels:{in:PEERS.map(p=>`N06.IN.${p}`),out:PEERS.map(p=>`N06.OUT.${p}`)}});}
export async function POST(request:Request){if(!authorized(request))return NextResponse.json({error:'Unauthorized'},{status:401});const raw=await request.text();if(new TextEncoder().encode(raw).byteLength>MAX_PAYLOAD_BYTES)return NextResponse.json({error:'SOUL_MESH_PAYLOAD_TOO_LARGE'},{status:413});let message:SoulMeshMessage;try{message=JSON.parse(raw) as SoulMeshMessage;}catch{return NextResponse.json({error:'INVALID_SOUL_MESH_JSON'},{status:400});}if(!validMessage(message))return NextResponse.json({error:'INVALID_SOUL_MESH_MESSAGE'},{status:400});try{return result(message,'response',await createN06Agents().execute(message));}catch(error){const detail=error instanceof Error?error.message:String(error);const code=detail.startsWith('N06_CAPABILITY_DENIED')?'CAPABILITY_DENIED':detail.startsWith('CAPABILITY_HANDLER_NOT_REGISTERED')?'CAPABILITY_NOT_IMPLEMENTED':detail.startsWith('UNKNOWN_TOOL')?'UNKNOWN_TOOL':detail==='N06_TOOL_CONTEXT_REQUIRED'?'CAPABILITY_CONTEXT_REQUIRED':'CAPABILITY_EXECUTION_ERROR';const status=code==='CAPABILITY_NOT_IMPLEMENTED'?501:code==='CAPABILITY_DENIED'?403:500;return result(message,'error',{code,message:detail},status);}}
